version: '3.8'
services:
    swim-api-3: 
        container_name: swim-api-alt3
        image: lagarnicachavira/swim-api-public:latest
        restart: always
        environment:
          NODE_ENV: production
          APPURL: localhost
          SERVERDESCRIPTION: Server Node 3 - production
          APPVERSION: 2.6.1
          LHOST: host.docker.internal
          LPORT: 3306
          LNAME: swim-logs
          LUSER: root
          LPASSWORD: changepassword
          LDIALECT: mysql
          UHOST: host.docker.internal
          UPORT: 3306
          UNAME: swim-users
          UUSER: root
          UPASSWORD: changepassword
          UDIALECT: mysql
          SHOST: host.docker.internal
          SPORT: 27017
          SNAME: swim-models
          SUSER: changeuser
          SPASSWORD: changepassword
          # swim admin user account
          AUSER: admin@email.com
          APASSWORD: adminpassword
          # guest user account
          GUSER: guest@email.com
          GPASSWORD: guestpassword
        ports:
          # <Local exposed port> : < application port running inside container>
          - '9113:3000'